# Generated by Django 4.1.4 on 2022-12-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ident', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('latitude_deg', models.FloatField(blank=True, default=0)),
                ('longitude_deg', models.FloatField(blank=True, default=0)),
                ('elevation_ft', models.IntegerField(blank=True, default=None, null=True)),
                ('continent', models.CharField(blank=True, default='', max_length=100)),
                ('iso_country', models.CharField(blank=True, default='', max_length=100)),
                ('iso_region', models.CharField(blank=True, default='', max_length=100)),
                ('municipality', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_service', models.CharField(blank=True, default='', max_length=100)),
                ('gps_code', models.CharField(blank=True, default='', max_length=100)),
                ('iata_code', models.CharField(blank=True, default='', max_length=100)),
                ('local_code', models.CharField(blank=True, default='', max_length=100)),
                ('home_link', models.URLField(blank=True, default='')),
                ('wikipedia_link', models.URLField(blank=True, default='')),
                ('keywords', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
